tilt_controller:
  controller:
    package: main_pkg 
    module: joint_position_controller 
    type: JointPositionController   
  joint_name: tilt_joint
  joint_speed: 1.0
  motor:
    id: 1
    init: 0 # 初始位置，对于4096分辨率的电机，0可能不是中心位置，通常是2048
    min: 0
    max: 4095